language: java
notifications:
  email:
    recipients:
      - bpogoriliy@gmail.com
jdk:
  - oraclejdk8
before_install:
    - chmod +x mvnw
install: travis_wait mvn install
deploy:
  provider: heroku
  app:
    master: messenger4j-app-bot
    dev: dev-chat-bot
script: HEROKU_API_KEY="$HEROKU_API_KEY" mvn clean spring-boot:run -Pheroku
