language: java
jdk: oraclejdk8

sudo: true
dist: trusty

jobs:
  include:
    - stage: build docker image
      script:
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - docker build -t twitter-stream-analysis .
      - docker images
      - docker tag twitter-stream-analysis $DOCKER_USERNAME/twitter-stream-analysis
      - docker push $DOCKER_USERNAME/twitter-stream-analysis
    - stage: test