version: '3.3'

services:
  web:
    build: .
    image: bobbbaich/twitter-stream-analysis
    container_name: twitter-stream-analysis
    ports:
      - 9999:8080
    working_dir: /app
    depends_on:
      - mongo
      - kafka

  mongo:
    image: mongo:3.2.4
    ports:
    - 27017:27017
    command: --smallfiles
    environment:
      - MONGOCLIENT_DEFAULT_CONNECTION_URL=mongodb://mongo:27017

  zookeeper:
    image: spotify/zookeeper
    ports:
      - 2181:2181
  kafka:
    image: spotify/kafka
    ports:
      - 9092:9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper
