version: '2'

services:
#  web:
#    build: .
#    image: csipon/twitter-stream-analysis
#    container_name: twitter-stream-analysis
#    ports:
#      - 9999:8080
#    working_dir: /
#    depends_on:
#      - mongo
#      - kafka

  mongo:
    image: mongo:3.2.4
    ports:
    - 27017:27017
    command: --smallfiles
    environment:
      - MONGOCLIENT_DEFAULT_CONNECTION_URL=mongodb://mongo:27017


  zookeeper:
    image: confluent/zookeeper
    ports:
      - 2181:2181

  kafka:
    image: confluent/kafka
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: tweet.t


  rest-proxy:
    image: confluent/rest-proxy
    depends_on:
      - zookeeper
      - kafka
    ports:
      - 8082:8082
    environment:
      RP_ZOOKEEPER_CONNECT: zookeeper:2181
      RP_SCHEMA_REGISTRY_URL: http://zookeeper:8081

#  schema-registry:
#    image: confluent/schema-registry
#    depends_on:
#      - kafka
#      - zookeeper
#    ports:
#      - 8081:8081
#    environment:
#      SR_KAFKASTORE_CONNECTION_URL: zookeeper:2181



docker run --rm -it -p 8000:8000 -e "KAFKA_REST_PROXY_URL=http://rest-proxy:8082" -e "PROXY=true" landoop/kafka-topics-ui