version: "2"

services:
#  web:
#    build: .
#    image: csipon/twitter-stream-analysis
#    container_name: twitter-stream-analysis
#    ports:
#      - 9999:8080
#    working_dir: /
#    depends_on:
#      - mongo
#      - kafkaserver

  mongo:
    image: mongo:3.2.4
    ports:
    - 27017:27017
    command: --smallfiles
    environment:
      - MONGOCLIENT_DEFAULT_CONNECTION_URL=mongodb://mongo:27017

  kafkaserver:
    image: "spotify/kafka:latest"
    container_name: kafka
    hostname: kafkaserver
#    networks:
#      - kafkanet
    ports:
      - 2181:2181
      - 9092:9092
    environment:
      ADVERTISED_HOST: kafkaserver
      ADVERTISED_PORT: 9092

  kafka_manager:
    image: "mzagar/kafka-manager-docker:1.3.3.4"
    container_name: kafkamanager
#    networks:
#      - kafkanet
    ports:
      - 9000:9000
    depends_on:
      - kafkaserver
    environment:
      ZK_HOSTS: "kafkaserver:2181"

#networks:
#  kafkanet:
#    driver: bridge