#---Profile Properties---
#Available profiles: local, remote, docker
#Set remote when deploy to server
server:
  port: 8080
spring:
  profiles:
    active: docker

messenger:
  greeting: "Hello {{user_full_name}}!\nYou can check any fact you want interacting with me!\nTap 'Get Started' and let's go!"
  getStartedPayload: "GET_STARTED_PAYLOAD"
  helpPayload: "HELP_PAYLOAD"