#Remote profile configuration
messenger4j:
  appSecret: ${MESSENGER_APP_SECRET}
  verifyToken: ${MESSENGER_VERIFY_TOKEN}
  pageAccessToken: ${MESSENGER_PAGE_ACCESS_TOKEN}
spring:
#Spring Data configuration
  data:
    mongodb:
      uri: ${MONGODB_URI}
  social:
      twitter:
        app-id: ${SOCIAL_TWITTER_APP_ID}
        app-secret: ${SOCIAL_TWITTER_APP_SECRET}
      facebook:
        app-id: ${SOCIAL_FACEBOOK_APP_ID}
        app-secret: ${SOCIAL_FACEBOOK_APP_SECRET}

