#---Profile Properties---
#Available profiles: local, remote
#Set remote when deploy to server
spring:
  profiles:
    active: local
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create-drop
##---Loggin Properties---
logging:
  level:
    org.springframework.web: INFO
    org.springframework.security: INFO
    org.springframework.batch: DEBUG
    com.bobbbaich: DEBUG
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){yellow} - %clr(%-4relative [%thread] %-5level %logger{35}){cyan} - %msg%n"

hibernate:
  dialect: org.hibernate.dialect.PostgreSQL9Dialect
  show_sql: true
  batch-size: 20
  hbm2ddl-auto: create-drop
  current-session-context-class: org.springframework.orm.hibernate5.SpringSessionContext
  default-schema: public

messenger:
  setup:
    getStartedButton: "Get Started"
    greeting: "Hello {{user_full_name}}!"

