#LOCAL profile configuration
messenger4j:
  appSecret: 1
  verifyToken: 1
  pageAccessToken: 1
spring:
  datasource:
      url: jdbc:postgresql://localhost:5432/social
      username: postgres
      password: postgres
      driver-class-name: org.postgresql.Driver
  social:
      twitter:
        app-id: 1TbklIzewbPjwqXwwvDohBXSd
        app-secret: R9xyjE0g7OUzZLBkVogLFwJaGzMIJ3Ab01i89gjdiGm51JCQuN
      facebook:
        app-id: 740743756119649
        app-secret: 2d6f7bfae3a55fbd05f05eb15e906d6d

