#---Profile Properties---
#Available profiles: local, remote
#Set remote when deploy to server
spring:
  profiles:
    active: local

security:
  oauth2:
    client:
      client-id: acme
      client-secret: acmesecret
      scope: read,write
      auto-approve-scopes: '.*'

#---Loggin Properties---
logging:
  level:
    org.springframework.web: INFO
    org.springframework.security: INFO
    com.bobbbaich: DEBUG
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){yellow} - %clr(%-4relative [%thread] %-5level %logger{35}){cyan} - %msg%n"

messenger:
  setup:
    getStartedButton: "Get Started"
    greeting: "Hello {{user_full_name}}!"