#---Profile Properties---
#Available profiles: local, remote, docker
#Set remote when deploy to server
spring:
  profiles:
    active: local
##---Loggin Properties---
logging:
  level:
    org.springframework.web: INFO
    org.springframework.social: DEBUG
    org.springframework.security: INFO
    org.springframework.batch: DEBUG
    org.springframework.web.servlet.mvc.method.annotation: ERROR
    org.springframework.boot.actuate.endpoint.mvc: ERROR
    com.bobbbaich: DEBUG

messenger:
  setup:
    getStartedButton: "Get Started"
    greeting: "Hello {{user_full_name}}!"

kafka:
  bootstrap-servers: localhost:9092
  topic:
    tweet: test

timeout:
  time: 10000
  thread:
    pool: 2