#Remote profile configuration
messenger4j:
  appSecret: ${MESSENGER_APP_SECRET}
  verifyToken: ${MESSENGER_VERIFY_TOKEN}
  pageAccessToken: ${MESSENGER_PAGE_ACCESS_TOKEN}
spring:
  social:
      twitter:
        app-id: ${SOCIAL_TWITTER_APP_ID}
        app-secret: ${SOCIAL_TWITTER_APP_SECRET}
      facebook:
        app-id: ${SOCIAL_FACEBOOK_APP_ID}
        app-secret: ${SOCIAL_FACEBOOK_APP_SECRET}
  data:
      mongodb:
        uri: mongodb://mongo:27017
        database: social

kafka:
  bootstrap-servers: PLAINTEXT://104.236.53.32:9092
  topic:
    tweet: test

timeout:
  time: 10000
  thread:
    pool: 2