#LOCAL profile configuration
messenger4j:
  appSecret: 1
  verifyToken: 1
  pageAccessToken: 1

spring:
#Spring Data configuration
  data:
    mongodb:
      uri: mongodb://127.0.0.1:27017/fbbot
  social:
      twitter:
        app-id: 1TbklIzewbPjwqXwwvDohBXSd
        app-secret: R9xyjE0g7OUzZLBkVogLFwJaGzMIJ3Ab01i89gjdiGm51JCQuN
      facebook:
        app-id: 1
        app-secret: 1

