#---Profile Properties---
#Available profiles: local, remote
#Set remote when deploy to server
spring:
  profiles:
    active: remote

security:
  oauth2:
    client:
      client-id: acme
      client-secret: acmesecret
      scope: read,write
      auto-approve-scopes: '.*'

facebook:
  client:
    accessTokenUri: https://graph.facebook.com/oauth/access_token
    userAuthorizationUri: https://www.facebook.com/dialog/oauth
    tokenName: oauth_token
    authenticationScheme: query
    clientAuthenticationScheme: form
  resource:
    userInfoUri: https://graph.facebook.com/me
#---Loggin Properties---
logging:
  level:
    org.springframework.web: INFO
    org.springframework.security: INFO
    com.bobbbaich: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"

messenger:
  setup:
    getStartedButton: "Get Started"
    greeting: "Hello {{user_full_name}}!"