sudo: true
dist: trusty

services:
  - docker

jobs:
  include:
    - stage: build docker image
      script:
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - docker build -t bot-kafka .
      - docker images
      - docker tag bot-kafka $DOCKER_USERNAME/bot-kafka
      - docker push $DOCKER_USERNAME/bot-kafka
#    - stage: delpoy to digital ocean
#      script:
#      - bash scripts/deploy.sh